# port 선언 (http://localhost:8081 로써 서버에 올라감)
server:
  port: 8081

# 해당 프로젝트 명칭 선언
spring:
  application:
    name: member
    
# hystrix timeout 시간조정 (1000 기본 -> 3000)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker: # hystrix circuitBreaker
        requestVolumeThreshold: 1
        errorThresholdPercentage: 50