# port 선언 (http://localhost:8082 로써 서버에 올라감)
server:
  port: 8082

# 해당 프로젝트 명칭 선언
spring:
  application:
    name: work

# eureka-client
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka